### ISSUE TITLE
Kubernetes version links are not shown correctly

### ISSUE THREAD

**Issue by mkorbi** [kubernetes/website#19892]
**This is a Bug Report**
**Problem:**
With the current version v1.18 you can see in drop down the old versions too.
<img width="373" alt="v18" src="https://user-images.githubusercontent.com/16919345/77702436-cf408880-6fb8-11ea-8799-67a6aed07c53.png">
If you switch to v1.17 then v1.18 doesn't appear:
<img width="382" alt="v17" src="https://user-images.githubusercontent.com/16919345/77702530-0a42bc00-6fb9-11ea-8e92-5ea5eed46056.png"> 
However, you can click on v1.17 and it redirects you back to latest/v1.18 version.

Further, with v1.16 everything is correct again
<img width="363" alt="v16" src="https://user-images.githubusercontent.com/16919345/77702596-2fcfc580-6fb9-11ea-888e-28290c972939.png">

I checked this with Google Chrome and Mozilla Firefox Browser.

**Proposed Solution:**

**Page to Update:**
I assume it has either something to do with the head file https://github.com/kubernetes/website/blob/67c0fb987eb5d48602cda1cf666452425f16bcc5/layouts/partials/header.html or with the config.toml https://github.com/kubernetes/website/blob/master/config.toml

**Comment by remyleone** [comment]
I think it is only with the v1.17 that there is a problem I can switch between all the other versions without problems except v1.17

**Comment by rlenferink** [comment]
Thanks for tracking @mkorbi. To me it seems this is more or less the same as #19841. Is that correct ?

**Comment by mkorbi** [comment]
@rlenferink looks like, but it doesn't seems to be fully solved with the merges mentioned

**Comment by kbhawkey** [comment]
Odd, from this page, I see 1.18 as the first in the list,
https://v1-17.docs.kubernetes.io/

**Comment by rlenferink** [comment]
I just had a look as well (Mozilla Firefox), and for me things are okay. It can be because different Netlify deployments are used for the subdomains (e.g. `v1-17.docs`). It could be that the 1.17 site was update a bit later. Maybe our technical leads can verify this on Netlify @kbhawkey @sftim?

For me viewing https://v1-17.docs.kubernetes.io/de/docs/home/ results in:
![afbeelding](https://user-images.githubusercontent.com/10008950/77783071-850ee400-7058-11ea-9c0d-b12f6167d374.png)

If things are working fine for you @mkorbi, you can close this PR with `/close`.

**Comment by kbhawkey** [comment]
The release-1.17 branch updates went in sometime this morning ( ~UTC - 5) today.

**Comment by reylejano-rxm** [comment]
> I just had a look as well (Mozilla Firefox), and for me things are okay. It can be because different Netlify deployments are used for the subdomains (e.g. `v1-17.docs`). It could be that the 1.17 site was update a bit later. Maybe our technical leads can verify this on Netlify @kbhawkey @sftim?
> 
> For me viewing https://v1-17.docs.kubernetes.io/de/docs/home/ results in:
> ![afbeelding](https://user-images.githubusercontent.com/10008950/77783071-850ee400-7058-11ea-9c0d-b12f6167d374.png)
> 
> If things are working fine for you @mkorbi, you can close this PR with `/close`.

I'm still seeing issues
![image](https://user-images.githubusercontent.com/52760880/77791397-c638d100-7023-11ea-8420-9503d9fb82bf.png)

**Comment by zacharysarah** [comment]
@reylejano-rxm The link is working fine for me. Maybe it was a CDN caching issue? Can you verify whether it's working for you now?

**Comment by reylejano-rxm** [comment]
@zacharysarah , I spun up a new VM and still get the errors.
I use this link to toggle between versions
https://kubernetes.io/docs/reference/scheduling/policies/
![image](https://user-images.githubusercontent.com/52760880/77806033-bed3f080-7040-11ea-825d-607533d57c81.png)

**Comment by zacharysarah** [comment]
@reylejano-rxm You're seeing an error because that URL is new in 1.18. If you like at [reference docs in 1.17](https://github.com/kubernetes/website/tree/release-1.17/content/en/docs/reference/), the scheduling directory doesn't exist.

So--it looks like the version selector is working as intended.

/close
