### ISSUE TITLE
"Play with Kubernetes" playground does not work

### ISSUE THREAD

**Issue by prasadkatti** [kubernetes/website#20810]
**This is a Bug Report**

**Problem:**
The website points to [Play with Kubernetes](https://labs.play-with-k8s.com/) playground links on multiple pages. Those links do not work for me. After I click the Start button on the site, I eventually get this message - 
> labs.play-with-k8s.com is currently unable to handle this request.

**Comment by zacharysarah** [comment]
@BenHall Are you not a member of the K8s org?

**Comment by BenHall** [comment]
@zacharysarah No, sadly not a member of the org.

In terms of "Play with Kubernetes". I wish I could help but this is an alternative to Katacoda and not something we are involved in.

**Comment by prasadkatti** [comment]
\cc playground folks - @ManoMarks @marcosnils

**Comment by ManoMarks** [comment]
I have not been involved in this project in over a year. I no longer work for the sponsor Docker. I am of not help on these things. I am saying this hoping it will stop someone  else from tagging me I. The future.

**Comment by marcosnils** [comment]
We were doing some maintenance on the service. The site should be working now.  @prasadkatti please confirm and close the issue

**Comment by prasadkatti** [comment]
@marcosnils - The links are working now. Thanks!

**Comment by kopparam-gagan** [comment]
Is there an issue with https://labs.play-with-k8s.com/
I have started a connection refused message.
![image (7)](https://user-images.githubusercontent.com/56405894/89107786-0cc68e00-d451-11ea-8580-5374529ef368.png)

**Comment by marcosnils** [comment]
That happens sometimes if the node is under pressure. Close the session and create a new one

**Comment by kopparam-gagan** [comment]
> That happens sometimes if the node is under pressure. Close the session and create a new one

I have tried this returning after a few hours now still no luck. is there a restriction on how many times we use it? like tied to usage by ID?

**Comment by kovvuriraghu** [comment]
> We were doing some maintenance on the service. The site should be working now. @prasadkatti please confirm and close the issue

Hi Marcosnils,

https://labs.play-with-k8s.com/ is not working and it is an giving below message 

This page isn’t workinglabs.play-with-k8s.com is currently unable to handle this request.
HTTP ERROR 500

**Comment by marcosnils** [comment]
Hey @kovvuriraghu . The environment was under some pressure. Just made some space for it to work better. Thx for reporting.

**Comment by kovvuriraghu** [comment]
> Hey @kovvuriraghu . The environment was under some pressure. Just made some space for it to work better. Thx for reporting.

Hi @marcosnils  ,  It is working  now. Thanks for your quick response.

**Comment by yogeek** [comment]
Hello @marcosnils , I am currently having some  trouble with https://labs.play-with-k8s.com : after clicking on `create an instance` it stays on `creating instance...` during a long time

**Comment by marcosnils** [comment]
Seems like there was a node that was not responding correctly. Mind trying now?

**Comment by yogeek** [comment]
yes it is better now, thanks @marcosnils !

**Comment by prasannavalluru** [comment]
how to come out of full screen

**Comment by shahamit** [comment]
Thanks for the quick fix. I can now create instances and execute kubectl commands. I do get an error when executing get nodes or get pods command as "The connection to the server localhost:8080 was refused - did you specify the right host or port?"

Looks like a configuration problem since it worked once after deleting the session and starting fresh but that was only 5 out of once that it worked. Rest of the times I get the connection refused error. Can you please have a look?

**Comment by marcosnils** [comment]
> I do get an error when executing get nodes or get pods command as "The connection to the server localhost:8080 was refused - did you specify the right host or port?"

Are you initializing the cluster?  You need to follow the instructions in the welcome message and make sure you have a running control plane before running kubectl commands.

**Comment by shahamit** [comment]
Yes I do run the first to commands in the welcome message to configure the
first node as the master node and later join this cluster from another node.

Anything else that I could be missing?

**Comment by marcosnils** [comment]
You can only use kubectl from the main node afterwards. All the secondary
nodes will through the error that you're seeing. That's how kubernetes
works.

**Comment by moz2nci** [comment]
Hello All, 

I am getting the same message when I tried to start: 
"labs.play-with-k8s.com is currently unable to handle this request.
HTTP ERROR 500" 

> > We were doing some maintenance on the service. The site should be working now. @prasadkatti please confirm and close the issue
> 
> Hi Marcosnils,
> 
> https://labs.play-with-k8s.com/ is not working and it is an giving below message
> 
> This page isn’t workinglabs.play-with-k8s.com is currently unable to handle this request. HTTP ERROR 500

**Comment by ninhpham0902** [comment]
> Hello All,
> 
> I am getting the same message when I tried to start: "labs.play-with-k8s.com is currently unable to handle this request. HTTP ERROR 500"
> 
> > > We were doing some maintenance on the service. The site should be working now. @prasadkatti please confirm and close the issue
> > 
> > 
> > Hi Marcosnils,
> > https://labs.play-with-k8s.com/ is not working and it is an giving below message
> > This page isn’t workinglabs.play-with-k8s.com is currently unable to handle this request. HTTP ERROR 500

I'm facing the same issue too

**Comment by RSwarnkar** [comment]
Website is DOWN again. Could you please check guys.

**Comment by marcosnils** [comment]
> Website is DOWN again. Could you please check guys.

no need to use caps. Sometimes the website is overloaded and you have to wait to access.

**Comment by ninhpham0902** [comment]
> > Website is DOWN again. Could you please check guys.
> 
> no need to use caps. Sometimes the website is overloaded and you have to wait to access.

actually the site has been down for a few days already :(

**Comment by marcosnils** [comment]
> actually the site has been down for a few days already :(

it's working now. Added a few more nodes.

**Comment by RSwarnkar** [comment]
ok, thanks @marcosnils Please don't mind capitals, Needed some attention hence used.

**Comment by RSwarnkar** [comment]
> > > Website is DOWN again. Could you please check guys.
> > 
> > 
> > no need to use caps. Sometimes the website is overloaded and you have to wait to access.
> 
> actually the site has been down for a few days already :(

True that !

**Comment by rakgup** [comment]
The site is up but not wokring.
Giving 404 for https://cdn.jsdelivr.net/gh/play-with-docker/sdk@master/dist/pwd.js

**Comment by marcosnils** [comment]
> The site is up but not wokring.

which site? 

both play-with-docker.com and play-with-k8s.com seem to work ok.

**Comment by rakgup** [comment]
> > The site is up but not wokring.
> 
> which site?
> 
> both play-with-docker.com and play-with-k8s.com seem to work ok.

https://training.play-with-kubernetes.com/kubernetes-workshop/

**Comment by s-titoo** [comment]
Hi all,

I see that issues was closed but ppl still got help.
Play with K8s is down for couple of days now.
Can someone pls have a look?
https://labs.play-with-k8s.com/

Thx a lot.

**Comment by marcosnils** [comment]
Hi, can you check now? Should be back online

**Comment by s-titoo** [comment]
Thx, Marcos - up and running. Nice day!

**Comment by sikoso** [comment]
Hi,
Once connected, Clicking on "Add New Instance", and it still shows "Creating" then nothing happens and becomes "Add New Instance".
Could you check please ?
Thank you,
/K

**Comment by alexritm** [comment]
node1 ~]$ kubectl port-forward hello 7788:80
Forwarding from 127.0.0.1:7788 -> 80

*****direct.labs.play-with-k8s.com didn’t send any data.   - no both http://  80 and 7788

Any thoughts?

**Comment by kathiresan-in** [comment]
Hi, Play with Kubernetes is down. please help to bring it up.
https://labs.play-with-k8s.com

**Comment by kmogal** [comment]
Hi !, play with k8s is down from 04th August. Help to bring it up. Thanks, kaleem

**Comment by sharkmerry7** [comment]
Seems play with k8s is still down :(. clicking add new instance spins and says creating. but nothing creates

**Comment by JediSange** [comment]
This is still happening for me.

**Comment by JediSange** [comment]
<img width="528" alt="Screen Shot 2022-09-03 at 7 17 54 PM" src="https://user-images.githubusercontent.com/832893/188290354-6167054d-6964-4792-bd38-3aea7140da35.png">

**Comment by Bimalnp4me** [comment]
cluster is down after few minutes , any idea ?  

[node1 ~]$ kubectl get nodes
NAME    STATUS   ROLES                  AGE     VERSION
node1   Ready    control-plane,master   3m32s   v1.20.1
node2   Ready    <none>                 89s     v1.20.1
[node1 ~]$ 
[node1 ~]$ kubectl cluster-info 
Kubernetes control plane is running at https://192.168.0.8:6443
KubeDNS is running at https://192.168.0.8:6443/api/v1/namespaces/kube-system/services/kube-dns:dns/proxy

To further debug and diagnose cluster problems, use 'kubectl cluster-info dump'.

[node1 dir]$ kubectl get nodes
The connection to the server 192.168.0.8:6443 was refused - did you specify the right host or port?
[node1 dir]$ kubectl cluster-info 

To further debug and diagnose cluster problems, use 'kubectl cluster-info dump'.
The connection to the server 192.168.0.8:6443 was refused - did you specify the right host or port?

**Comment by amanarora08** [comment]
Hi, Play with Kubernetes is down. please help to bring it up.
https://labs.play-with-k8s.com/

**Comment by AmarNathChary** [comment]
Adding comments on the closed issue also is not helping people to know as the notification will go to only those who have been involved in that issue

**Comment by bvenu2020** [comment]
I am getting this error. The Connection to the server localhost:8080 was refused - did you specify the right host or port?

**Comment by tharindukw96** [comment]
> I am getting this error. The Connection to the server localhost:8080 was refused - did you specify the right host or port?

You have to bootstrap the cluster. Read instructions on the terminal.

`kubeadm init --apiserver-advertise-address $(hostname -i) --pod-network-cidr 10.5.0.0/16`
`kubectl apply -f https://raw.githubusercontent.com/cloudnativelabs/kube-router/master/daemonset/kubeadm-kuberouter.yaml`

**Comment by 1111841** [comment]
Hi, I am getting error to access this website.

**Comment by AmarNathChary** [comment]
> Hi, I am getting error to access this website.

hi, @1111841 sometimes https://labs.play-with-k8s.com/ website is temporarily down. It's working now, please take a look.

**Comment by vijayphalgun** [comment]
Ran the example nginx pods but they are always in pending state  [node1 /]$ kubectl get pods
NAME                       READY   STATUS    RESTARTS   AGE
my-nginx-cbdccf466-2ldrc   0/1     Pending   0          19m
my-nginx-cbdccf466-8pfkj   0/1     Pending   0          19m
my-nginx-cbdccf466-vj795   0/1     Pending   0          19m

**Comment by marcosnils** [comment]
you need to add at least a worker node for the pods to be schedulable. Cheers!
